In [37]:
import pandas as pd

In [38]:
df=pd.read_csv(r"C:\Users\AYSHA NASARIN\OneDrive\Documents\day17_demo.csv")
df.shape

(15, 8)

In [39]:
df.head(15)

,OrderID,Date,Region,Product,Category,Sales,Profit,Quantity
0,1001,2024-01-05,South,Avil Milk Classic,Beverages,450,80,10
1,1002,2024-01-06,North,Chocolate Shake,Beverages,600,120,15
2,1003,2024-01-07,East,Strawberry Milk,Beverages,300,40,8
3,1004,2024-01-08,West,Avil Milk Premium,Beverages,750,200,20
4,1005,2024-01-09,South,Cold Coffee,Beverages,500,60,12
5,1006,2024-01-10,North,Vanilla Shake,Beverages,650,150,18
6,1007,2024-01-11,East,Black Tea,Beverages,200,30,6
7,1008,2024-01-12,West,Green Tea,Beverages,350,70,9
8,1009,2024-01-13,South,Avil Milk Special,Beverages,800,250,22
9,1010,2024-01-14,North,Chocolate Shake,Beverages,550,90,14
10,1011,2024-01-15,East,Strawberry Milk,Beverages,400,60,11
11,1012,2024-01-16,West,Cold Coffee,Beverages,700,180,19
12,1013,2024-01-17,South,Vanilla Shake,Beverages,480,75,13
13,1014,2024-01-18,North,Avil Milk Premium,Beverages,900,300,25
14,1015,2024-01-19,East,Black Tea,Beverages,220,35,7

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   OrderID   15 non-null     int64
 1   Date      15 non-null     object
 2   Region    15 non-null     object
 3   Product   15 non-null     object
 4   Category  15 non-null     object
 5   Sales     15 non-null     int64
 6   Profit    15 non-null     int64
 7   Quantity  15 non-null     int64
dtypes: int64(4), object(4)
memory usage: 1.1+ KB

In [41]:
df[['Product','Profit']] 
# This shows only product names and their profits, helping focus on product performance.

              Product  Profit
0   Avil Milk Classic      80
1     Chocolate Shake     120
2     Strawberry Milk      40
3   Avil Milk Premium     200
4         Cold Coffee      60
5       Vanilla Shake     150
6           Black Tea      30
7           Green Tea      70
8   Avil Milk Special     250
9     Chocolate Shake      90
10    Strawberry Milk      60
11        Cold Coffee     180
12      Vanilla Shake      75
13  Avil Milk Premium     300
14          Black Tea      35

In [42]:
df[df['Sales'] > df['Sales'].mean()]
# This filters transactions where sales are above average, highlighting high-performing sales.

,OrderID,Date,Region,Product,Category,Sales,Profit,Quantity
1,1002,2024-01-06,North,Chocolate Shake,Beverages,600,120,15
3,1004,2024-01-08,West,Avil Milk Premium,Beverages,750,200,20
5,1006,2024-01-10,North,Vanilla Shake,Beverages,650,150,18
8,1009,2024-01-13,South,Avil Milk Special,Beverages,800,250,22
9,1010,2024-01-14,North,Chocolate Shake,Beverages,550,90,14
11,1012,2024-01-16,West,Cold Coffee,Beverages,700,180,19
13,1014,2024-01-18,North,Avil Milk Premium,Beverages,900,300,25

In [43]:
df.sort_values(by='Sales', ascending=False)
# This sorts the dataset from highest to lowest sales, helping identify top-performing transactions.

,OrderID,Date,Region,Product,Category,Sales,Profit,Quantity
13,1014,2024-01-18,North,Avil Milk Premium,Beverages,900,300,25
8,1009,2024-01-13,South,Avil Milk Special,Beverages,800,250,22
3,1004,2024-01-08,West,Avil Milk Premium,Beverages,750,200,20
11,1012,2024-01-16,West,Cold Coffee,Beverages,700,180,19
5,1006,2024-01-10,North,Vanilla Shake,Beverages,650,150,18
1,1002,2024-01-06,North,Chocolate Shake,Beverages,600,120,15
9,1010,2024-01-14,North,Chocolate Shake,Beverages,550,90,14
4,1005,2024-01-09,South,Cold Coffee,Beverages,500,60,12
12,1013,2024-01-17,South,Vanilla Shake,Beverages,480,75,13
0,1001,2024-01-05,South,Avil Milk Classic,Beverages,450,80,10
10,1011,2024-01-15,East,Strawberry Milk,Beverages,400,60,11
7,1008,2024-01-12,West,Green Tea,Beverages,350,70,9
2,1003,2024-01-07,East,Strawberry Milk,Beverages,300,40,8
14,1015,2024-01-19,East,Black Tea,Beverages,220,35,7
6,1007,2024-01-11,East,Black Tea,Beverages,200,30,6

In [44]:
df[(df['Sales'] > 500) & (df['Profit'] > 100)]
# This shows transactions with both high sales and high profit, indicating the most valuable business deals.

,OrderID,Date,Region,Product,Category,Sales,Profit,Quantity
1,1002,2024-01-06,North,Chocolate Shake,Beverages,600,120,15
3,1004,2024-01-08,West,Avil Milk Premium,Beverages,750,200,20
5,1006,2024-01-10,North,Vanilla Shake,Beverages,650,150,18
8,1009,2024-01-13,South,Avil Milk Special,Beverages,800,250,22
11,1012,2024-01-16,West,Cold Coffee,Beverages,700,180,19
13,1014,2024-01-18,North,Avil Milk Premium,Beverages,900,300,25